version: 0.2

env:
  variables:
    S3_BUCKET: "easyshop-frontend-bucket-production"          # Replace with your S3 bucket
    AWS_REGION: "us-east-1"                 # e.g., us-east-1
    CLOUDFRONT_DIST_ID: "E1BMHGV5X7L7QF" # Replace with your CloudFront distribution ID

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo Deploying build to S3 bucket $S3_BUCKET...
      - aws s3 sync build/ s3://$S3_BUCKET --region $AWS_REGION --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
      - echo Deployment complete!

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - node_modules/**/*
